# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graft < Formula
  desc "Agentless deployment tool extending Docker Compose to cloud via SSH"
  homepage "https://github.com/the-graft-project/graft"
  version "2.4.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-Graft-Project/Graft/releases/download/v2.4.8/Graft_2.4.8_Darwin_amd64.tar.gz"
      sha256 "5c841ba9f1ef66bfcb46c92e872e690a316b1488dcf72dca9a0cb3632c2ad3d2"

      define_method(:install) do
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-Graft-Project/Graft/releases/download/v2.4.8/Graft_2.4.8_Darwin_arm64.tar.gz"
      sha256 "c694cc9b904a5e28a56dd8d729b31d16fe517d424f09e24256a10df19954eb67"

      define_method(:install) do
        bin.install "graft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-Graft-Project/Graft/releases/download/v2.4.8/Graft_2.4.8_Linux_amd64.tar.gz"
      sha256 "afc9134298540181cd86917fe4fb48191f512997ca8fb1b3163299a46d856b95"
      define_method(:install) do
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-Graft-Project/Graft/releases/download/v2.4.8/Graft_2.4.8_Linux_arm64.tar.gz"
      sha256 "0e137671a5a6a89a3e974cde31c799a9e138b3809a9bdaf40b117c634b1f2595"
      define_method(:install) do
        bin.install "graft"
      end
    end
  end

  test do
    system "#{bin}/graft --version"
  end
end
