# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graft < Formula
  desc "Agentless deployment tool extending Docker Compose to cloud via SSH"
  homepage "https://github.com/the-graft-project/graft"
  version "2.5.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-Graft-Project/Graft/releases/download/v2.5.5/Graft_2.5.5_Darwin_amd64.tar.gz"
      sha256 "9aa7760ce52f94c8f475bee4346a33bb0c6188170e4f8db1bbe078d80c06cac4"

      define_method(:install) do
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-Graft-Project/Graft/releases/download/v2.5.5/Graft_2.5.5_Darwin_arm64.tar.gz"
      sha256 "83cb04458b5d883746f8929b1ac82a7680cc7782454106e66d6789caa69970c1"

      define_method(:install) do
        bin.install "graft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-Graft-Project/Graft/releases/download/v2.5.5/Graft_2.5.5_Linux_amd64.tar.gz"
      sha256 "414ebb8f0eaa0dab0cb7de0313f41f102685253a0d5598153b0dde84b0633f45"
      define_method(:install) do
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-Graft-Project/Graft/releases/download/v2.5.5/Graft_2.5.5_Linux_arm64.tar.gz"
      sha256 "a9ad275333313174347c80db1c2268d87ca35dd0a55e7dd74a7d73e2dd0aab0c"
      define_method(:install) do
        bin.install "graft"
      end
    end
  end

  test do
    system "#{bin}/graft --version"
  end
end
