# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graft < Formula
  desc "Agentless deployment tool extending Docker Compose to cloud via SSH"
  homepage "https://github.com/the-graft-project/graft"
  version "2.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-Graft-Project/Graft/releases/download/v2.5.2/Graft_2.5.2_Darwin_amd64.tar.gz"
      sha256 "9c33f076435324cf36038304205d0707742ef5fec613f5b56faeee92a9d1329b"

      define_method(:install) do
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-Graft-Project/Graft/releases/download/v2.5.2/Graft_2.5.2_Darwin_arm64.tar.gz"
      sha256 "b6b2d4057f9319fc791d8b3bb106b0d38612e8035b7978647e6b3501297ac4c7"

      define_method(:install) do
        bin.install "graft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-Graft-Project/Graft/releases/download/v2.5.2/Graft_2.5.2_Linux_amd64.tar.gz"
      sha256 "4720ca7dad9aac9c13da2025d2fe77787041449e79ca8c342b28ed111fb819b0"
      define_method(:install) do
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-Graft-Project/Graft/releases/download/v2.5.2/Graft_2.5.2_Linux_arm64.tar.gz"
      sha256 "46ee9de5250948102d79aac64d1145c191905ddf2c5ff6522c5cd7904e607ff9"
      define_method(:install) do
        bin.install "graft"
      end
    end
  end

  test do
    system "#{bin}/graft --version"
  end
end
